config/routes.rb
Rails.application.routes.draw do
  resources :feeds do
    collection do
      post:confirm
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :users,only: [:new,:create,:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
   mount_uploader :image, ImageUploader
   validates :title, presence: true
   validates :content, presence: true
   belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  validates :name,
             presence: true, length: { maximum: 30 }
  validates :email,
             presence: true, length: { maximum: 255 },
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :feeds

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]
  before_action :check

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    
  end

  # GET /feeds/new
  def new
    if params[:back]
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = current_user.feeds.build(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm
    @feed =  Feed.new(feed_params)
    @feed.user_id = current_user.id
    render :new if @feed.invalid?
    # @feed = current_user.feed.build(feed_params)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_feed
    @feed = Feed.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def feed_params
    params.require(:feed).permit(:image, :image_cache, :title, :content)
  end

  def check
    if current_user.nil?
      @session = new_session_path
      redirect_to @session
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user =
    User.find_by(email: params[:session][:email].downcase)
    # binding.pry
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "confirm"
      confirm_feeds_path
    elsif action_name == "edit"
      feed_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    # binding.pry
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true,url:choose_new_or_edit) do |form| %>

  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @feed,
                url: feeds_path,
              local: true) do |form| %>
  <!-- 確認画面でアップロードした画像を表示させるための記述 -->
  <%= image_tag(@feed.image.url) if @feed.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

<br>
<p>タイトル:<%= @feed.title %></p>
<p>本文:<%= @feed.content %></p>
  <%= form.submit "投稿する" %>
<% end %>

<%= form_with(model:@feed,
                url:new_feed_path,
              local:true,
             method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      
      <th>Title</th>
      <th>Content</th>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.image %></td>
        <td><%= feed.title %></td>
        <td><%= feed.content %></td>
        <td><%= feed.user.name %></td>
        <td><%= link_to '「しょうさい」', feed %></td>
        <td><%= link_to '「へんしゅう」', edit_feed_path(feed) %></td>
        <td><%= link_to '「けす」', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <br>
  <% @feed.image %>
  <%= image_tag @feed.image.url if @feed.image.present? %>

  <br>
  <strong>title:</strong>
  <br>
  <%= @feed.title %>
  <br>
  <strong>content:</strong>
  <br>
  <%= @feed.content %>







</p>

<%= link_to '「へんしゅう」', edit_feed_path(@feed) %> |
<%= link_to '「もどる」', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsExam2</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name = "viewport" content = "width = device-width">
  </head>

  <body>
    <header class = "header">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
              <span class="sr-only">Bootstrap</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><%= image_tag("logo2.png", :class => "logo_image col-md-6") %></a>
          </div>
          <div id="gnavi" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><a href="">top</a></li>
              <li><a href="">メニュー</a></li>
              <% if logged_in? %>
　　　　　         <li><%= link_to '新しくfeedsを投稿する', new_feed_path %></li>
              <% end %>


    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
  </ul>
</div>
</div>
</nav>
  </header>

    <%= yield %>

  </body>
</html>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id=“error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %>
       prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <div class="form-group">
  <%= f.submit "Create my account" %>
  </div>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>